### ISSUE TITLE
UI toggle to disable/remove pickup duration

### ISSUE THREAD

**Issue by yrgithb** [yrgithb/gipsykings#32]
Provide an UI toggle to disable pickup duration completely so that boulders are picked up instantaneously.

**Comment by sasoh** [comment]
Already added with [this commit](https://github.com/yrgithb/gipsykings/commit/7b3142169b4de5d8aceebb6bbded91f6d2fa1ebf). Not persistent between restarts, though. Will fix this tonight.

**Comment by sasoh** [comment]
Working.
